apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zhurwbigk-nodejs 
  janus-idp.io/tekton: zhurwbigk-nodejs
  backstage.io/kubernetes-id: zhurwbigk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zhurwbigk-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml